/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppWriteupsIndexRouteImport } from './routes/_app.writeups.index'
import { Route as AppWriteupsNewRouteImport } from './routes/_app.writeups.new'
import { Route as AppWriteupsSlugRouteImport } from './routes/_app.writeups.$slug'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppWriteupsIndexRoute = AppWriteupsIndexRouteImport.update({
  id: '/writeups/',
  path: '/writeups/',
  getParentRoute: () => AppRoute,
} as any)
const AppWriteupsNewRoute = AppWriteupsNewRouteImport.update({
  id: '/writeups/new',
  path: '/writeups/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWriteupsSlugRoute = AppWriteupsSlugRouteImport.update({
  id: '/writeups/$slug',
  path: '/writeups/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/writeups/$slug': typeof AppWriteupsSlugRoute
  '/writeups/new': typeof AppWriteupsNewRoute
  '/writeups/': typeof AppWriteupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/writeups/$slug': typeof AppWriteupsSlugRoute
  '/writeups/new': typeof AppWriteupsNewRoute
  '/writeups': typeof AppWriteupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/writeups/$slug': typeof AppWriteupsSlugRoute
  '/_app/writeups/new': typeof AppWriteupsNewRoute
  '/_app/writeups/': typeof AppWriteupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/team'
    | '/writeups/$slug'
    | '/writeups/new'
    | '/writeups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/team'
    | '/writeups/$slug'
    | '/writeups/new'
    | '/writeups'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/writeups/$slug'
    | '/_app/writeups/new'
    | '/_app/writeups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writeups/': {
      id: '/_app/writeups/'
      path: '/writeups'
      fullPath: '/writeups/'
      preLoaderRoute: typeof AppWriteupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writeups/new': {
      id: '/_app/writeups/new'
      path: '/writeups/new'
      fullPath: '/writeups/new'
      preLoaderRoute: typeof AppWriteupsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writeups/$slug': {
      id: '/_app/writeups/$slug'
      path: '/writeups/$slug'
      fullPath: '/writeups/$slug'
      preLoaderRoute: typeof AppWriteupsSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWriteupsSlugRoute: typeof AppWriteupsSlugRoute
  AppWriteupsNewRoute: typeof AppWriteupsNewRoute
  AppWriteupsIndexRoute: typeof AppWriteupsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppWriteupsSlugRoute: AppWriteupsSlugRoute,
  AppWriteupsNewRoute: AppWriteupsNewRoute,
  AppWriteupsIndexRoute: AppWriteupsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
