/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinInvite_codeRouteImport } from './routes/join.$invite_code'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as UUsernameIndexRouteImport } from './routes/u.$username.index'
import { Route as AppWriteupsIndexRouteImport } from './routes/_app.writeups.index'
import { Route as AppEventsIndexRouteImport } from './routes/_app.events.index'
import { Route as UUsernameSlugRouteImport } from './routes/u.$username.$slug'
import { Route as AppWriteupsNewRouteImport } from './routes/_app.writeups.new'
import { Route as AppWriteupsSlugRouteImport } from './routes/_app.writeups.$slug'
import { Route as AppEventsNewRouteImport } from './routes/_app.events.new'
import { Route as AppEventsIdRouteImport } from './routes/_app.events.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInvite_codeRoute = JoinInvite_codeRouteImport.update({
  id: '/join/$invite_code',
  path: '/join/$invite_code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/u/$username/',
  path: '/u/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWriteupsIndexRoute = AppWriteupsIndexRouteImport.update({
  id: '/writeups/',
  path: '/writeups/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const UUsernameSlugRoute = UUsernameSlugRouteImport.update({
  id: '/u/$username/$slug',
  path: '/u/$username/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWriteupsNewRoute = AppWriteupsNewRouteImport.update({
  id: '/writeups/new',
  path: '/writeups/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWriteupsSlugRoute = AppWriteupsSlugRouteImport.update({
  id: '/writeups/$slug',
  path: '/writeups/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIdRoute = AppEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/join/$invite_code': typeof JoinInvite_codeRoute
  '/events/$id': typeof AppEventsIdRoute
  '/events/new': typeof AppEventsNewRoute
  '/writeups/$slug': typeof AppWriteupsSlugRoute
  '/writeups/new': typeof AppWriteupsNewRoute
  '/u/$username/$slug': typeof UUsernameSlugRoute
  '/events/': typeof AppEventsIndexRoute
  '/writeups/': typeof AppWriteupsIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/join/$invite_code': typeof JoinInvite_codeRoute
  '/events/$id': typeof AppEventsIdRoute
  '/events/new': typeof AppEventsNewRoute
  '/writeups/$slug': typeof AppWriteupsSlugRoute
  '/writeups/new': typeof AppWriteupsNewRoute
  '/u/$username/$slug': typeof UUsernameSlugRoute
  '/events': typeof AppEventsIndexRoute
  '/writeups': typeof AppWriteupsIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/join/$invite_code': typeof JoinInvite_codeRoute
  '/_app/events/$id': typeof AppEventsIdRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/writeups/$slug': typeof AppWriteupsSlugRoute
  '/_app/writeups/new': typeof AppWriteupsNewRoute
  '/u/$username/$slug': typeof UUsernameSlugRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/writeups/': typeof AppWriteupsIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/team'
    | '/join/$invite_code'
    | '/events/$id'
    | '/events/new'
    | '/writeups/$slug'
    | '/writeups/new'
    | '/u/$username/$slug'
    | '/events/'
    | '/writeups/'
    | '/u/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/team'
    | '/join/$invite_code'
    | '/events/$id'
    | '/events/new'
    | '/writeups/$slug'
    | '/writeups/new'
    | '/u/$username/$slug'
    | '/events'
    | '/writeups'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/team'
    | '/join/$invite_code'
    | '/_app/events/$id'
    | '/_app/events/new'
    | '/_app/writeups/$slug'
    | '/_app/writeups/new'
    | '/u/$username/$slug'
    | '/_app/events/'
    | '/_app/writeups/'
    | '/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  JoinInvite_codeRoute: typeof JoinInvite_codeRoute
  UUsernameSlugRoute: typeof UUsernameSlugRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$invite_code': {
      id: '/join/$invite_code'
      path: '/join/$invite_code'
      fullPath: '/join/$invite_code'
      preLoaderRoute: typeof JoinInvite_codeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/writeups/': {
      id: '/_app/writeups/'
      path: '/writeups'
      fullPath: '/writeups/'
      preLoaderRoute: typeof AppWriteupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/u/$username/$slug': {
      id: '/u/$username/$slug'
      path: '/u/$username/$slug'
      fullPath: '/u/$username/$slug'
      preLoaderRoute: typeof UUsernameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/writeups/new': {
      id: '/_app/writeups/new'
      path: '/writeups/new'
      fullPath: '/writeups/new'
      preLoaderRoute: typeof AppWriteupsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writeups/$slug': {
      id: '/_app/writeups/$slug'
      path: '/writeups/$slug'
      fullPath: '/writeups/$slug'
      preLoaderRoute: typeof AppWriteupsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$id': {
      id: '/_app/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AppEventsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppEventsIdRoute: typeof AppEventsIdRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppWriteupsSlugRoute: typeof AppWriteupsSlugRoute
  AppWriteupsNewRoute: typeof AppWriteupsNewRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppWriteupsIndexRoute: typeof AppWriteupsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppEventsIdRoute: AppEventsIdRoute,
  AppEventsNewRoute: AppEventsNewRoute,
  AppWriteupsSlugRoute: AppWriteupsSlugRoute,
  AppWriteupsNewRoute: AppWriteupsNewRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppWriteupsIndexRoute: AppWriteupsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  JoinInvite_codeRoute: JoinInvite_codeRoute,
  UUsernameSlugRoute: UUsernameSlugRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
